# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs
require 'open-uri'
require 'active_record/fixtures'

Cart.create([
  { :created_at => nil, :updated_at => nil }
], :without_protection => true )

Comment.create([
  { :description => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )

Category.create([
  { :name => "Toys", :description => nil, :created_at => nil, :updated_at => nil},
  { :name => "Clothes", :description => nil, :created_at => nil, :updated_at => nil },
  { :name => "Sports-Outdoors", :description => nil, :created_at => nil, :updated_at => nil},
  { :name => "Food", :description => nil, :created_at => nil, :updated_at => nil },
  { :name => "Office Supplies", :description => nil, :created_at => nil, :updated_at => nil },
  { :name => "Electronics", :description => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )

open("#{Rails.root}/db/items_to_be_seeded.txt") do | items |
  items.read.each_line do | item |
    name, description, price, brand, brandimage, image, image1, image2, categories = item.chomp.split("|")
    i = Item.create!(:name => name, :description => description, :price => price, :brand => brand, :brandimage => brandimage, :image => image, :image1 => image1, :image2 => image2)
    categories.chomp.split(',').each do |category|
      puts category
      i.categories << Category.where(:name=>category)
      puts Category.where(:name=>category)
    end
  end
end

Review.create([
  { :title => nil, :rating => nil, :description => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



User.create([
  { :email => "127ajr@gmail.com", :encrypted_password => "$2a$10$ySFynNEHVMC9ltl2.MIcxORgKvDu1AEbRiEBMvKMUxERnqc93QVWy", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 1, :current_sign_in_at => "2013-05-08 21:25:14", :last_sign_in_at => "2013-05-08 21:25:14", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :created_at => "2013-05-08 21:25:14", :updated_at => "2013-05-08 21:25:14", :first_name => "Albert", :last_name => "Rodenius" },
  { :email => "albertr@mit.edu", :encrypted_password => "$2a$10$Xfm5kK6ERgu85/SmZC8DXewKjYDgTXIsduvD6FPrbl6jfjkAfsmBK", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 1, :current_sign_in_at => "2013-05-12 19:46:30", :last_sign_in_at => "2013-05-12 19:46:30", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :created_at => "2013-05-12 19:46:30", :updated_at => "2013-05-12 19:46:30", :first_name => "a", :last_name => "r" }
], :without_protection => true )

