# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Cart.create([
  { :created_at => nil, :updated_at => nil }
], :without_protection => true )



Category.create([
  { :name => nil, :description => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



Comment.create([
  { :description => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



Item.create([
  { :name => "Baby Einstein Bendy Ball", :price => 5.99, :description => "The Baby Einstein Bendy Ball features bright primary colors and the recognizable Caterpillar character on center band. Soft, flexible plastic make this ball both durable and fun and the Bendy Ball's design makes it easy for little fingers to grasp and roll. The multi-colored rolling Rattle Ball inside adds additional sounds and visual stimulation to this toy.", :brand => "Baby Einstein", :created_at => "2013-05-08 21:02:01", :updated_at => "2013-05-08 21:02:01", :category => "toys", :image => "http://ecx.images-amazon.com/images/I/71Ehhcw421L._SL1500_.jpg", :image1 => "http://ecx.images-amazon.com/images/I/71IdGWGLD0L._SL1500_.jpg", :image2 => "http://ecx.images-amazon.com/images/I/71A9tla0mPL._SL1500_.jpg" },
  { :name => "Munchkin Fun Ice Soothing Ring Teether", :price => 1.79, :description => "Teething is tough...for you and your baby. So soothe their tender gums with our incredibly cool frozen teether. Place from freezer to gums and in no time babies will be chewing and cooing their way to happiness. Features: Provides relief for tender gums Fun shape makes it inviting to chew Easy to grasp for little hands Ideal for 0 - 24 months.", :brand => "Munchkin", :created_at => "2013-05-08 21:14:39", :updated_at => "2013-05-08 21:14:39", :category => "toys", :image => "http://ecx.images-amazon.com/images/I/51Un7geLLLL._SY355_.jpg", :image1 => "http://ecx.images-amazon.com/images/I/51BaA8QkSRL.jpg", :image2 => "http://ecx.images-amazon.com/images/I/51Un7geLLLL.jpg" },
  { :name => "Syma S107/S107G R/C Helicopter - Blue", :price => 20.09, :description => "This Brand New 3 Channel mini rc helicopter is the world's newest, most durable and stable helicopter. The item comes with the latest gyro system for precision control. The metal frame has proven to withstand dozens of crashes. The mini helicopter charges directly from the controller which uses \"AA\" batteries and has a full-function trim control for the perfect flight. Get one today before they all fly away! The Syma S107 metal frame series with gyroscope takes indoor flying to the next level through precision control. It is extremely easy to fly and durable. This is highly recommended for beginners. No flight training necessary.", :brand => "Syma", :created_at => "2013-05-08 21:16:16", :updated_at => "2013-05-08 21:16:16", :category => "toys", :image => "http://ecx.images-amazon.com/images/I/31sUYSIICVL._SY445_.jpg", :image1 => "http://ecx.images-amazon.com/images/I/31qcpmteYmL.jpg", :image2 => "http://ecx.images-amazon.com/images/I/31XSeUKZKCL.jpg" },
  { :name => "Ultra Stomp Rocket", :price => 14.54, :description => "Stomp on the Launch Pad and a blast of air propels the Stomp Rocket over 200 feet in the air! The kit contains 4 rockets with the OG-1 Nosecone.", :brand => "DL Company", :created_at => "2013-05-08 21:17:30", :updated_at => "2013-05-08 21:17:30", :category => "toys", :image => "http://ecx.images-amazon.com/images/I/313vp%2BSU3hL.jpg", :image1 => "http://ecx.images-amazon.com/images/I/61WAebmPsoL.jpg", :image2 => "http://ecx.images-amazon.com/images/I/61LW63MtqRL.jpg" },
  { :name => "Spalding NBA Street Basketball", :price => 39.99, :description => "Take your game to the streets with Spalding NBA Street performance outdoor basketball,designed specifically to withstand the rough-and-tumble street game. This basketball has a durable cover and structure to stand up to rigorous pick up games at the park or in the driveway.", :brand => "Spalding", :created_at => "2013-05-08 21:18:50", :updated_at => "2013-05-08 21:18:50", :category => "Spalding", :image => "http://ecx.images-amazon.com/images/I/91FDDJ%2BH1PL._SL1500_.jpg", :image1 => "http://ecx.images-amazon.com/images/I/91FDDJ%2BH1PL._SL1500_.jpg", :image2 => "http://ecx.images-amazon.com/images/I/91FDDJ%2BH1PL._SL1500_.jpg" }
], :without_protection => true )



Review.create([
  { :title => nil, :rating => nil, :description => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



User.create([
  { :email => "127ajr@gmail.com", :encrypted_password => "$2a$10$ySFynNEHVMC9ltl2.MIcxORgKvDu1AEbRiEBMvKMUxERnqc93QVWy", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 1, :current_sign_in_at => "2013-05-08 21:25:14", :last_sign_in_at => "2013-05-08 21:25:14", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :created_at => "2013-05-08 21:25:14", :updated_at => "2013-05-08 21:25:14", :first_name => "Albert", :last_name => "Rodenius" },
  { :email => "albertr@mit.edu", :encrypted_password => "$2a$10$Xfm5kK6ERgu85/SmZC8DXewKjYDgTXIsduvD6FPrbl6jfjkAfsmBK", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 1, :current_sign_in_at => "2013-05-12 19:46:30", :last_sign_in_at => "2013-05-12 19:46:30", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :created_at => "2013-05-12 19:46:30", :updated_at => "2013-05-12 19:46:30", :first_name => "a", :last_name => "r" }
], :without_protection => true )


